name: Installation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies Mac
      run: make mac

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies Ubuntu
      run: make ubuntu
