name: Installation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      chosen-os:
        description: "OS to run on"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - macos-latest

jobs:
  install-script:
    runs-on: ${{ inputs.chosen-os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run Install script
      run: ./install.sh
